apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: fluent-bit-config
  files:
  - fluent-bit.conf
  - parsers.conf

images:
- name: fluent/fluent-bit
  newTag: 1.6.10

namespace: logging

patchesStrategicMerge:
- resources.yml

resources:
- ../../../logging
