apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: fluent-bit
  app.kubernetes.io/instance: fluent-bit

resources:
- clusterrole.yml
- clusterrolebinding.yml
- daemonset.yml
- service.yml
- serviceaccount.yml
