apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
- 0-fluent-bit-role-binding.yaml
- 0-fluent-bit-role.yaml
- 0-fluent-bit-service-account.yaml
- 0-fluent-bit-service.yaml
- 1-fluent-bit-config.yaml
- 2-fluent-bit-ds.yaml
#- service.yaml