apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  template:
    spec:
      containers:
      - name: fluent-bit
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 75m
            memory: 50Mi
