apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: fluent/fluent-bit
  newTag: 1.6.10

namespace: logging

resources:
- ../../base

configMapGenerator:
- name: fluent-bit-config
  files:
  - input-kubernetes.conf
  - output-elasticsearch.conf
  - parsers.conf
  - filter-kubernetes.conf
  - fluent-bit.conf

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    k8s-app: fluent-bit
