apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 0-fluent-bit-role-binding.yaml
- 0-fluent-bit-role.yaml
- 0-fluent-bit-service-account.yaml
- 0-fluent-bit-service.yaml
- 2-fluent-bit-ds.yaml